POST http://localhost:3001/api/blogs 
Content-Type: application/json

# {
#   "title": "New Blog",
#   "author": "Jane Doe",
#   "url": "http://example.com",
#   "likes": 12
# },
{
  "title": "New Blog",
  "author": "johndoe",
  "name": "John Doe",
  "url": "http://example.com",
  "password": "supersecret"
}

